const Posts = [
    {
        id:'1',
        userName: 'Jenny Doe',
        userImg: require('../assets/images/person1.jpg'),
        postTime: '4 mins ago',
        post:'Hey there, this is my test for post of my social app - Instant-community',
        postImg: require('../assets/images/person2.jpg'),
        liked:true,
        likes:'14',
        comments:'5',
        saved:false,
        saves:'23',
        shared:true,
        shares:'40',
        docViewed: false,
        docViews: '20',
        video: 'none'
    },
    {
        id:'2',
        userName: 'John Doe',
        userImg: require('../assets/images/person2.jpg'),
        postTime: '45 mins ago',
        post:'Hey there, this is my test for post of my social app - Instant-community',
        postImg: 'none',
        liked:false,
        likes:'7',
        comments:'0',
        saved:false,
        saves:'0',
        shared:false,
        shares:'0',
        docViewed: true,
        docViews: '20',
        video: 'none'
    },
    {
        id:'3',
        userName: 'Jasmine Park',
        userImg: require('../assets/images/person3.jpg'),
        postTime: '4 mins ago',
        post:'Updated profile',
        postImg: require('../assets/images/person3.jpg'),
        liked:true,
        likes:'1',
        comments:'5',
        saved:true,
        saves:'1',
        shared:true,
        shares:'2',
        docViewed: true,
        docViews: '2',
        video: 'none'
    },
    {
        id:'4',
        userName: 'Kenpachi Zaraki',
        userImg: require('../assets/images/person1.jpg'),
        postTime: '4 mins ago',
        post:'the second Kenpachi',
        postImg: require('../assets/images/person2.jpg'),
        liked:false,
        likes:'22',
        comments:'5',
        saved:true,
        saves:'3',
        shared:false,
        shares:'10',
        docViewed: false,
        docViews: '10',
        video: 'none'
    },
    {
        id:'5',
        userName: 'Gojo Satoru',
        userImg: require('../assets/images/person3.jpg'),
        postTime: '4 mins ago',
        post:'Feel better.',
        postImg: require('../assets/images/person3.jpg'),
        liked:false,
        likes:'123',
        comments:'78',
        saved:false,
        saves:'23',
        shared:true,
        shares:'40',
        docViewed: true,
        docViews: '20',
    },
    {
        id:'6',
        userName: 'Gojo Satoru',
        userImg: require('../assets/images/person3.jpg'),
        postTime: '4 mins ago',
        post:'New Trend.',
        postImg: 'none',
        liked:false,
        likes:'123',
        comments:'78',
        saved:false,
        saves:'23',
        shared:true,
        shares:'40',
        docViewed: true,
        docViews: '20',
        video: 'https://www.youtube.com/watch?v=1amVwnbuObo'
    },
]
export default Posts;